server:
  port: 9091

#I want the application work on eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:

  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    #password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver     #driver for mysql connection

  jpa:
    hibernate:
      #if there are change on the database it will be updated and not create all the table again
      ddl-auto: update  #create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #convert orm language to mysql querry